blank_issues_enabled: false
contact_links:
  - name: Preguntas o soporte
    url: https://github.com/federico-winter/Lubricantro/issues/new?labels=question
    about: Para consultas generales, abre un issue con la etiqueta "question".
